apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
nameSuffix: -crm-280-call
commonLabels:
  symbol: crm-280-call
configMapGenerator:
  - name: tda-alerter-cm
    behavior: replace
    files:
      - alert.yaml
