apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
nameSuffix: -tsla-1020-put
commonLabels:
  symbol: tsla-1020-put
configMapGenerator:
  - name: tda-alerter-cm
    behavior: replace
    files:
      - alert.yaml
