# app id from your TD Ameritrade developer website
# the "@AMER>OAUTHAP" part is fixed
apiKey: YOUR_APP@AMER.OAUTHAP
# if empty, no slack notifications will be sent
# register a webhook how-to: https://api.slack.com/messaging/webhooks
slackWebhookUrl: https://register.and.replace/from/above