apiVersion: batch/v1
kind: CronJob
metadata:
  #  namespace: tda-alerter
  name: tda-alert-job
  labels:
    app: tda-alerter
spec:
  jobTemplate:
    metadata:
      name: tda-alert-job
      labels:
        app: tda-alerter
    spec:
      template:
        metadata:
          labels:
            app: tda-alerter
        spec:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
            runAsGroup: 1001
          volumes:
            - name: combined-volume
              projected:
                sources:
                  - secret:
                      name: tda-alerter-secrets
                  - configMap:
                      name: tda-alerter-cm
          containers:
            - image: registry.digitalocean.com/agrande-default-cr/aperepel/tda-alerter:latest
              name: tda-alerter
              volumeMounts:
                - mountPath: /app/conf
                  name: combined-volume
          restartPolicy: OnFailure
  # Every 15 minutes, starting at 30 minutes past the hour,
  # at 06:00 AM through 12:59 PM and 01:00 PM, Monday through Friday
  schedule: 30/15 6-12,13 * * MON-FRI
  failedJobsHistoryLimit: 4
  successfulJobsHistoryLimit: 4
  concurrencyPolicy: Replace